//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHopDong.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Hop_Dong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hop_Dong()
        {
            this.Nghiem_Thu = new HashSet<Nghiem_Thu>();
            this.Phu_Luc = new HashSet<Phu_Luc>();
        }
    
        public int ID_Hop_Dong { get; set; }

        [Display(Name ="Tên hợp đồng")]
        public string Ten_Hop_Dong { get; set; }
        [Display(Name = "Loại hợp đồng")]
        public Nullable<int> ID_Loai_Hop_Dong { get; set; }
        [Display(Name = "Tên công ty")]
        public string Ten_Cong_Ty { get; set; }
        [Display(Name = "ngày ký hợp đồng")]
        public Nullable<System.DateTime> Ngay_Ky_Hop_Dong { get; set; }
        [Display(Name = "Ngày kết thúc hợp đồng")]
        public Nullable<System.DateTime> Ngay_Ket_Thuc { get; set; }
        [Display(Name = "Hàng hóa")]
        public Nullable<int> ID_Hang_Hoa { get; set; }
        [Display(Name = "Số lượng")]
        public Nullable<int> So_Luong { get; set; }
        [Display(Name = "Đơn giá")]
        public Nullable<decimal> Don_Gia { get; set; }
        [Display(Name = "Thành tiền")]
        public Nullable<decimal> Thanh_Tien { get; set; }
        [Display(Name = "Trạng thái")]
        public string Trang_Thai { get; set; }
        [Display(Name = "Người tạo")]
        public Nullable<int> Nguoi_Tao_HD { get; set; }
        [Display(Name = "Ngày tạo")]
        public Nullable<System.DateTime> Ngay_Tao_HD { get; set; }
        public Nullable<int> Nguoi_Cap_Nhat { get; set; }
        public Nullable<System.DateTime> Ngay_Cap_Nhat { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
    
        public virtual Hang_Hoa Hang_Hoa { get; set; }
        public virtual Loai_Hop_Dong Loai_Hop_Dong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nghiem_Thu> Nghiem_Thu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phu_Luc> Phu_Luc { get; set; }
    }
}
