//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHopDong.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Loai_Hop_Dong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Loai_Hop_Dong()
        {
            this.Hop_Dong = new HashSet<Hop_Dong>();
        }

        [Display(Name = "Loại hợp đồng")]
        public int ID_Loai_Hop_Dong { get; set; }
        [Display(Name = "Tên loại hợp đồng")]
        public string Ten_Loai_Hop_Dong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hop_Dong> Hop_Dong { get; set; }
    }
}
