//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHopDong.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Phu_Luc
    {
        public int ID_Phu_Luc { get; set; }
        [Display(Name = "Số phụ lục")]
        public string So_Phu_Luc { get; set; }
        [Display(Name = "Ngày ký phụ lục")]
        public Nullable<System.DateTime> Ngay_Ky { get; set; }
        [Display(Name = "Người tạo phụ lục")]
        public Nullable<int> Nguoi_Tao_Phu_Luc { get; set; }
        [Display(Name = "Người ký phụ lục")]
        public string Nguoi_Ky_Phu_Luc { get; set; }
        [Display(Name = "Giá trị hợp đồng trước")]
        public Nullable<decimal> Gia_Tri_HD_Truoc { get; set; }
        [Display(Name = "Giá trị hợp đồng sau")]
        public Nullable<decimal> Gia_Tri_HD_Sau { get; set; }
        [Display(Name = "Hợp đồng")]
        public Nullable<int> ID_Hop_Dong { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
    
        public virtual Hop_Dong Hop_Dong { get; set; }
    }
}
