//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHopDong.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyHopDongDBContext : DbContext
    {
        public QuanLyHopDongDBContext()
            : base("name=QuanLyHopDongDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hang_Hoa> Hang_Hoa { get; set; }
        public virtual DbSet<Hop_Dong> Hop_Dong { get; set; }
        public virtual DbSet<Loai_Hang> Loai_Hang { get; set; }
        public virtual DbSet<Loai_Hop_Dong> Loai_Hop_Dong { get; set; }
        public virtual DbSet<Nghiem_Thu> Nghiem_Thu { get; set; }
        public virtual DbSet<Nguoi_Dung> Nguoi_Dung { get; set; }
        public virtual DbSet<Phu_Luc> Phu_Luc { get; set; }
    }
}
